<a href="https://colab.research.google.com/github/Rs-Biranchi/Micro-credit/blob/main/Copy_of_2_Project_micro_credit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#loading required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import roc_curve,roc_auc_score

import warnings
warnings.filterwarnings('ignore')

In [ ]:
Data_new=pd.read_csv('/content/drive/My Drive/Colab Notebooks/micro_credit.csv')
Data_new

Unnamed: 0  label     aon  ...  medianamnt_loans90  payback30  payback90
0                0      0   272.0  ...                 0.0  29.000000  29.000000
1                1      1   712.0  ...                 0.0   0.000000   0.000000
2                2      1   535.0  ...                 0.0   0.000000   0.000000
3                3      1   241.0  ...                 0.0   0.000000   0.000000
4                4      1   947.0  ...                 0.0   2.333333   2.333333
...            ...    ...     ...  ...                 ...        ...        ...
193954      209588      1   404.0  ...                 0.0   1.000000   1.000000
193955      209589      1  1075.0  ...                 0.0   1.000000   1.000000
193956      209590      1  1013.0  ...                 0.0   4.000000   3.833333
193957      209591      1  1732.0  ...                 0.0   0.000000  10.500000
193958      209592      1  1581.0  ...                 0.0   0.000000   0.000000

[193959 rows x 32 columns]

In [ ]:
Data_new.drop('Unnamed: 0',axis=1,inplace=True)
print(Data_new.shape)
print(Data_new.head())

(193959, 31)
   label    aon  daily_decr30  ...  medianamnt_loans90  payback30  payback90
0      0  272.0   3055.050000  ...                 0.0  29.000000  29.000000
1      1  712.0  12122.000000  ...                 0.0   0.000000   0.000000
2      1  535.0   1398.000000  ...                 0.0   0.000000   0.000000
3      1  241.0     21.228000  ...                 0.0   0.000000   0.000000
4      1  947.0    150.619333  ...                 0.0   2.333333   2.333333

[5 rows x 31 columns]


In [ ]:
#Splitting the dataset into training and testing sets.
x=Data_new.drop('label',axis=1)
x

aon  daily_decr30  ...  payback30  payback90
0        272.0   3055.050000  ...  29.000000  29.000000
1        712.0  12122.000000  ...   0.000000   0.000000
2        535.0   1398.000000  ...   0.000000   0.000000
3        241.0     21.228000  ...   0.000000   0.000000
4        947.0    150.619333  ...   2.333333   2.333333
...        ...           ...  ...        ...        ...
193954   404.0    151.872333  ...   1.000000   1.000000
193955  1075.0     36.936000  ...   1.000000   1.000000
193956  1013.0  11843.111667  ...   4.000000   3.833333
193957  1732.0  12488.228333  ...   0.000000  10.500000
193958  1581.0   4489.362000  ...   0.000000   0.000000

[193959 rows x 30 columns]

In [ ]:
Y=Data_new.loc[:,'label'].values.reshape(-1,1)
Y

array([[0],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [ ]:
#Scaling the training set
sc=StandardScaler()
X=sc.fit_transform(x)
X=pd.DataFrame(X,columns=x.columns)
X

aon  daily_decr30  ...  payback30  payback90
0      -0.762925     -0.235077  ...   4.922885   3.971182
1       0.118823      0.983884  ...  -0.540521  -0.564642
2      -0.235880     -0.457851  ...  -0.540521  -0.564642
3      -0.825048     -0.642944  ...  -0.540521  -0.564642
4       0.589757     -0.625549  ...  -0.100936  -0.199691
...          ...           ...  ...        ...        ...
193954 -0.498400     -0.625381  ...  -0.352127  -0.408235
193955  0.846265     -0.640833  ...  -0.352127  -0.408235
193956  0.722019      0.946391  ...   0.213053   0.034921
193957  2.162875      1.033120  ...  -0.540521   1.077639
193958  1.860275     -0.042248  ...  -0.540521  -0.564642

[193959 rows x 30 columns]

In [ ]:
#Checking the best random State
max_acc_scr=0
for r_state in range(42,101):
  X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=r_state)
  lr=LogisticRegression()
  lr.fit(X_train,Y_train)
  pred=lr.predict(X_test)
  acc_scr=accuracy_score(Y_test,pred)
  if acc_scr>max_acc_scr:
    max_acc_scr=acc_scr
    final_r_state=r_state
  print('Max accuracy score corresponding to ',final_r_state,' is ',max_acc_scr)

Max accuracy score corresponding to  42  is  0.8759881762562728
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43  is  0.8764178181068262
Max accuracy score corresponding to  43 

In [ ]:
#Accuracy score is maximum when the random_state is 69. So we take random_state 69 for final splitting

In [ ]:
#Checking if the model is over or under fitting
a_score=cross_val_score(lr,X,Y,scoring='f1',cv=5)
print(a_score)
print(a_score.mean())

[0.93232978 0.93259751 0.93296732 0.93260701 0.93311162]
0.9327226494334784


In [ ]:
A_score=cross_val_score(lr,X,Y,scoring='accuracy',cv=5)
print(A_score)
print(A_score.mean())

[0.87414931 0.87469066 0.8753609  0.87466488 0.87556392]
0.8748859329960789


In [ ]:
#Model is well fitted

In [ ]:
#Final splitting
train_X,test_X,train_Y,test_Y=train_test_split(X,Y,random_state=69,test_size=0.3)

In [ ]:
model=[LogisticRegression(),KNeighborsClassifier(),SVC()]
for m in model:
  m.fit(train_X,train_Y)
  predm=m.predict(test_X)
  print("Accuracy Score of ",m, ' is :')
  print(accuracy_score(test_Y,predm))
  print("Confusion Matrix: \n",confusion_matrix(test_Y,predm))
  print("Classification Report: \n",classification_report(test_Y,predm))
  print("\n")

Accuracy Score of  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)  is :
0.876658417543136
Confusion Matrix: 
 [[  423  6799]
 [  378 50588]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.53      0.06      0.11      7222
           1       0.88      0.99      0.93     50966

    accuracy                           0.88     58188
   macro avg       0.70      0.53      0.52     58188
weighted avg       0.84      0.88      0.83     58188



Accuracy Score of  KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')  is :
0.876469375128

In [ ]:
model=[RandomForestClassifier(),GradientBoostingClassifier()]
for m in model:
  m.fit(train_X,train_Y)
  predm=m.predict(test_X)
  print("Accuracy Score of ",m, ' is :')
  print(accuracy_score(test_Y,predm))
  print("Confusion Matrix: \n",confusion_matrix(test_Y,predm))
  print("Classification Report: \n",classification_report(test_Y,predm))
  print("\n")

Accuracy Score of  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)  is :
0.9121812057468894
Confusion Matrix: 
 [[ 3214  4008]
 [ 1102 49864]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.74      0.45      0.56      7222
           1       0.93      0.98      0.95     50966

    accuracy                           0.91     58188
   macro avg       0.84      0.71      0.75     58188
weighted avg       0.90      0.91      0.90     58188



Accu

Among the upper 5 models RandomForestClassifier performs best in terms of Accuracy Score,Precision,recall and F1 score. So we take the model as final model to classify the label.

In [ ]:
rf=RandomForestClassifier()
params={'n_estimators':[50,100,150,200,250,300,350,400]}
gd_sr=GridSearchCV(estimator=rf,param_grid=params,cv=5,scoring='recall')
gd_sr.fit(train_X,train_Y)
best_param=gd_sr.best_params_ 
print(best_param)
best_score=gd_sr.best_score_
print(best_score)

{'n_estimators': 400}
0.9805808152803234


In [ ]:
rf=RandomForestClassifier()
params={'n_estimators':[400,450],'criterion':['gini','entropy']}
gd_sr=GridSearchCV(estimator=rf,param_grid=params,cv=5,scoring='recall')
gd_sr.fit(train_X,train_Y)
best_param=gd_sr.best_params_
print(best_param)
best_score=gd_sr.best_score_
print(best_score)

{'criterion': 'gini', 'n_estimators': 450}
0.9804626654107877


In [ ]:
#Final Model
rfc=RandomForestClassifier(n_estimators=400,criterion='gini')
rfc.fit(train_X,train_Y)
pred_rfc=rfc.predict(test_X)
print("Accuracy Score : ",accuracy_score(test_Y,pred_rfc))
print("Confusion Matrix: \n",confusion_matrix(test_Y,pred_rfc))
print("Classification Report: \n",classification_report(test_Y,pred_rfc))

Accuracy Score of:  0.9126795902935313
Confusion Matrix: 
 [[ 3194  4028]
 [ 1053 49913]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.75      0.44      0.56      7222
           1       0.93      0.98      0.95     50966

    accuracy                           0.91     58188
   macro avg       0.84      0.71      0.75     58188
weighted avg       0.90      0.91      0.90     58188



In [ ]:
print('Prediction: ',pred_rfc)

Prediction:  [1 1 1 ... 1 1 1]


In [ ]:
#Saving the prediction in a csv file
df=pd.DataFrame(pred_rfc)
df.to_csv('Micro_credit_prediction.csv')

In [ ]:
#Saving the model for further use
from sklearn.externals import joblib
joblib.dump(rfc,'Micro_credict_prediction_model.obj')

['Micro_credict_prediction_model.obj']